# Generated by Django 3.1.7 on 2021-06-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasencabezados',
            name='canalCompra',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='facturasencabezados',
            name='numeroProductosComprados',
            field=models.IntegerField(null=True),
        ),
    ]
