# Generated by Django 3.1.7 on 2021-05-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasdetalles',
            name='descuento',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='facturasdetalles',
            name='impuesto',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='facturasdetalles',
            name='precio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='facturasdetalles',
            name='valorUnitario',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='facturasencabezados',
            name='descuento',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='facturasencabezados',
            name='iva',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='facturasencabezados',
            name='subTotal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='facturasencabezados',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
