# Generated by Django 3.1.7 on 2021-06-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_facturas', '0002_auto_20210614_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasencabezados',
            name='numeroFactura',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
