# Generated by Django 3.1.7 on 2021-06-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_facturas', '0003_auto_20210621_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasdetalles',
            name='valorDescuento',
            field=models.FloatField(null=True),
        ),
    ]
