# Generated by Django 3.1.7 on 2021-06-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_facturas', '0004_facturasdetalles_valordescuento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturasdetalles',
            old_name='informacionAdicinal',
            new_name='informacionAdicional',
        ),
    ]
