# Generated by Django 3.1.7 on 2021-08-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_facturas', '0006_facturasdetalles_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturasencabezados',
            old_name='canalCompra',
            new_name='canal',
        ),
    ]
