# Generated by Django 3.1.7 on 2021-11-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_facturas', '0007_auto_20210824_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasdetalles',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
