# Generated by Django 3.1.7 on 2024-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_facturas', '0009_auto_20240123_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasencabezados',
            name='courier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
