# Generated by Django 3.1.7 on 2021-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_parametrizaciones', '0002_auto_20210721_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrizaciones',
            name='maximo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parametrizaciones',
            name='minimo',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
