# Generated by Django 3.1.7 on 2021-10-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_parametrizaciones', '0005_auto_20211025_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrizaciones',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='parametrizaciones',
            name='valor',
            field=models.CharField(max_length=255),
        ),
    ]
