# Generated by Django 3.1.7 on 2021-10-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_categorias', '0002_auto_20210831_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
