# Generated by Django 3.1.7 on 2024-01-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_categorias', '0003_auto_20211026_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='estado',
            field=models.CharField(default='Inactivo', max_length=150),
        ),
    ]
