# Generated by Django 3.1.7 on 2021-08-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdo_prediccionCrosseling', '0002_delete_detallescrosseling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalles',
            old_name='prediccionesCrosseling',
            new_name='prediccionCrosseling',
        ),
    ]
