# Generated by Django 3.1.7 on 2021-08-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdo_prediccionCrosseling', '0004_prediccioncrosseling_factura_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccioncrosseling',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
