# Generated by Django 3.1.7 on 2024-01-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdp_productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precioOferta',
            field=models.FloatField(null=True),
        ),
    ]
