# Generated by Django 3.1.7 on 2024-01-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdp_productos', '0002_productos_preciooferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='subtitulo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='titulo',
            field=models.TextField(null=True),
        ),
    ]
