# Generated by Django 3.1.7 on 2024-01-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdp_productos', '0003_auto_20240119_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='codigo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
