# Generated by Django 3.1.7 on 2021-05-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_roles', '0002_auto_20210429_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
