# Generated by Django 3.1.7 on 2021-08-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negocio', models.SmallIntegerField(null=True)),
                ('cliente', models.SmallIntegerField(null=True)),
                ('codigoOferta', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateField(null=True)),
                ('nombres', models.CharField(max_length=150, null=True)),
                ('apellidos', models.CharField(max_length=150, null=True)),
                ('identificacion', models.CharField(max_length=150, null=True)),
                ('telefono', models.CharField(max_length=150, null=True)),
                ('correo', models.EmailField(max_length=150, null=True)),
                ('vigenciaOferta', models.IntegerField(max_length=150, null=True)),
                ('canalVentas', models.CharField(max_length=150, null=True)),
                ('calificacionCliente', models.CharField(max_length=150, null=True)),
                ('indicadorCliente', models.CharField(max_length=150, null=True)),
                ('personaGenera', models.CharField(max_length=150, null=True)),
                ('descripcion', models.CharField(max_length=150, null=True)),
                ('total', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaDetalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150, null=True)),
                ('producto', models.CharField(max_length=150, null=True)),
                ('precio', models.CharField(max_length=150, null=True)),
                ('descuento', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='mdo_generarOferta.oferta')),
            ],
        ),
    ]
