# Generated by Django 3.1.7 on 2021-08-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdo_generarOferta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertadetalles',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
