# Generated by Django 3.1.7 on 2021-08-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdo_generarOferta', '0003_auto_20210816_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertadetalles',
            name='cantidad',
            field=models.SmallIntegerField(null=True),
        ),
    ]
