# Generated by Django 3.1.7 on 2021-08-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdo_generarOferta', '0005_auto_20210824_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertadetalles',
            name='valorDescuento',
            field=models.FloatField(null=True),
        ),
    ]
