# Generated by Django 3.1.7 on 2021-08-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdo_generarOferta', '0006_ofertadetalles_valordescuento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='canalVentas',
            new_name='canal',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='personaGenera',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='fechaOferta',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='codigoOferta',
            new_name='numeroFactura',
        ),
        migrations.RenameField(
            model_name='ofertadetalles',
            old_name='producto',
            new_name='articulo',
        ),
        migrations.AddField(
            model_name='oferta',
            name='nombreVendedor',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='numeroProductosComprados',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='razonSocial',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipoIdentificacion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ofertadetalles',
            name='impuesto',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ofertadetalles',
            name='informacionAdicional',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ofertadetalles',
            name='valorUnitario',
            field=models.FloatField(null=True),
        ),
    ]
