# Generated by Django 3.1.7 on 2021-11-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdo_generarOferta', '0009_auto_20211028_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertadetalles',
            old_name='articulo',
            new_name='producto',
        ),
        migrations.AlterField(
            model_name='oferta',
            name='vigenciaOferta',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
