# Generated by Django 3.1.7 on 2024-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0002_pedidos_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='calificacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='entregoProducto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fechaEntrega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='horaEntrega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
