# Generated by Django 3.1.7 on 2024-03-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0003_auto_20240302_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='codigoConfirmacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fechaHoraConfirmacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='metodoConfirmacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='subtotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='tipoFacturacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
