# Generated by Django 3.1.7 on 2024-03-06 17:49

import apps.WOOCOMMERCE.woocommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0004_auto_20240305_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='archivoGuia',
            field=models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.woocommerce.models.upload_path),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='canalEnvio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='codigoCourier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='confirmacionEnvio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='nombreCourier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
