# Generated by Django 3.1.7 on 2024-03-07 21:27

import apps.WOOCOMMERCE.woocommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0006_pedidos_correocourier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='videoGuia',
            field=models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.woocommerce.models.upload_path),
        ),
    ]
