# Generated by Django 3.1.7 on 2024-03-08 14:22

import apps.WOOCOMMERCE.woocommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0007_pedidos_videoguia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='videoGuia',
            new_name='fotoEmpaque',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='videoEmpaque',
            field=models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.woocommerce.models.upload_path),
        ),
    ]
