# Generated by Django 3.1.7 on 2024-03-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0009_pedidos_codigovendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='urlMetodoPago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
