# Generated by Django 3.1.7 on 2024-03-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0013_pedidos_archivometodopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='verificarPedido',
            field=models.BooleanField(default=False),
        ),
    ]
