# Generated by Django 3.1.7 on 2024-03-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0014_pedidos_verificarpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='numeroGuia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
