# Generated by Django 3.1.7 on 2024-04-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0015_pedidos_numeroguia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='verificarGeneracionGuia',
            field=models.BooleanField(default=False),
        ),
    ]
