# Generated by Django 3.1.7 on 2024-04-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0016_pedidos_verificargeneracionguia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fechaEmpacado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
