# Generated by Django 3.1.7 on 2024-04-10 15:07

import apps.WOOCOMMERCE.woocommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0017_pedidos_fechaempacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='guiServiEntrega',
            field=models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.woocommerce.models.upload_path),
        ),
    ]
