# Generated by Django 3.1.7 on 2024-04-25 20:18

import apps.WOOCOMMERCE.woocommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0018_pedidos_guiservientrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='evidenciaPago',
            field=models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.woocommerce.models.upload_path),
        ),
    ]
