# Generated by Django 3.1.7 on 2024-04-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0019_pedidos_evidenciapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='tipoPago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
