# Generated by Django 3.1.7 on 2024-05-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0020_pedidos_tipopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('codigoBarras', models.CharField(blank=True, max_length=150, null=True)),
                ('caracteristicas', models.CharField(blank=True, max_length=250, null=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('bodega', models.CharField(blank=True, max_length=150, null=True)),
                ('imagen', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(blank=True, max_length=150, null=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='woocommerce.pedidos')),
            ],
        ),
    ]
