# Generated by Django 3.1.7 on 2024-06-04 22:04

import apps.WOOCOMMERCE.woocommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0021_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fotoCupon',
            field=models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.woocommerce.models.upload_path),
        ),
    ]
