# Generated by Django 3.1.7 on 2024-07-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0022_pedidos_fotocupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='gestion_despacho',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='gestion_pedido',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
