# Generated by Django 3.1.7 on 2024-07-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0024_pedidos_tipoenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
