# Generated by Django 3.1.7 on 2024-07-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0026_auto_20240729_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fechaCargaFormaPago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
