# Generated by Django 3.1.7 on 2024-07-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0027_pedidos_fechacargaformapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='numeroComprobante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
