# Generated by Django 3.1.7 on 2024-07-31 14:39

import apps.WOOCOMMERCE.woocommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0028_pedidos_numerocomprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='archivoFactura',
            field=models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.woocommerce.models.upload_path),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='montoSubtotalCliente',
            field=models.FloatField(null=True),
        ),
    ]
