# Generated by Django 3.1.7 on 2024-07-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0029_auto_20240731_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fechaEmisionFactura',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='motivoNegacionPedido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
