# Generated by Django 3.1.7 on 2024-08-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0030_auto_20240731_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='montoSubtotalAprobado',
            field=models.FloatField(null=True),
        ),
    ]
