# Generated by Django 3.1.7 on 2024-08-08 15:55

import apps.WOOCOMMERCE.woocommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0031_pedidos_montosubtotalaprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='archivoFacturaQueja',
            field=models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.woocommerce.models.upload_path),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='descripcionQueja',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fechaCargaFormaPagoQueja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fechaEmisionFacturaQueja',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='montoSubtotalQueja',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='tipoPagoQueja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
