# Generated by Django 3.1.7 on 2024-08-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0032_auto_20240808_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='numeroComprobanteQueja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
