# Generated by Django 3.1.7 on 2024-08-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0033_pedidos_numerocomprobantequeja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='montoSubtotalAprobadoQueja',
            field=models.FloatField(null=True),
        ),
    ]
