# Generated by Django 3.1.7 on 2024-08-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0034_pedidos_montosubtotalaprobadoqueja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='comision',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='comisionFinal',
            field=models.FloatField(null=True),
        ),
    ]
