# Generated by Django 3.1.7 on 2024-08-15 17:29

import apps.WOOCOMMERCE.woocommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0035_auto_20240812_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='comprobanteVendedorGmb',
            field=models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.woocommerce.models.upload_path),
        ),
    ]
