# Generated by Django 3.1.7 on 2024-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woocommerce', '0036_pedidos_comprobantevendedorgmb'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='nombreEnvio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
