# Generated by Django 3.1.7 on 2021-11-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdo_parametrizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrizaciones',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
