# Generated by Django 3.1.7 on 2021-08-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdo_prediccionRefil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccionrefil',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
