# Generated by Django 3.1.7 on 2021-10-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdo_prediccionRefil', '0002_prediccionrefil_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles',
            name='informacionAdicional',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='prediccionrefil',
            name='apellidos',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prediccionrefil',
            name='correo',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prediccionrefil',
            name='identificacion',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='prediccionrefil',
            name='nombres',
            field=models.CharField(max_length=255),
        ),
    ]
