# Generated by Django 3.1.7 on 2021-04-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150, null=True)),
                ('tipo', models.CharField(max_length=150, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=250, null=True)),
                ('config', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('idPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vittoria_catalogo.catalogo')),
            ],
        ),
    ]
