# Generated by Django 3.1.7 on 2024-10-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='canal',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
