# Generated by Django 3.1.7 on 2024-10-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_catalogo', '0002_catalogo_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='tiempo_entrega',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
