# Generated by Django 3.1.7 on 2021-05-20 16:17

import apps.MDM.mdm_clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_clientes', '0002_auto_20210518_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='foto',
        ),
        migrations.AddField(
            model_name='clientes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.MDM.mdm_clientes.models.upload_path),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='gastosPromedioMensual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ingresosPromedioMensual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parientes',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parientes',
            name='gastosPromedioMensual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parientes',
            name='ingresosPromedioMensual',
            field=models.FloatField(null=True),
        ),
    ]
