# Generated by Django 3.1.7 on 2021-05-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_clientes', '0005_auto_20210521_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(default='Inactivo', max_length=200),
        ),
        migrations.AlterField(
            model_name='parientes',
            name='estado',
            field=models.CharField(default='Inactivo', max_length=200),
        ),
    ]
