# Generated by Django 3.1.7 on 2021-06-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_clientes', '0008_auto_20210608_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='apellidos',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nombres',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
