# Generated by Django 3.1.7 on 2021-08-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_clientes', '0009_auto_20210608_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
