# Generated by Django 3.1.7 on 2021-10-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_clientes', '0012_auto_20211021_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfisicosclientes',
            name='piso',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
