# Generated by Django 3.1.7 on 2024-01-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_clientes', '0014_auto_20240122_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='tipoIdentificacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
