# Generated by Django 3.1.7 on 2024-06-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_clientes', '0015_clientes_tipoidentificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cedula',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
