# Generated by Django 3.1.7 on 2024-10-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_clientes', '0016_auto_20240610_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='callePrincipal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='calleSecundaria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='gps',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='referencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
