# Generated by Django 3.1.7 on 2021-10-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_parametrizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrizaciones',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='parametrizaciones',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parametrizaciones',
            name='tipo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='parametrizaciones',
            name='tipoVariable',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='parametrizaciones',
            name='valor',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
