# Generated by Django 3.1.7 on 2024-01-19 19:14

import apps.MDM.mdm_parametrizaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_parametrizaciones', '0002_auto_20211021_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrizaciones',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.MDM.mdm_parametrizaciones.models.upload_path),
        ),
    ]
