# Generated by Django 3.1.7 on 2024-07-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('valor', models.CharField(max_length=250, null=True)),
                ('pedidos_local', models.JSONField(null=True)),
                ('pedidos_omniglobal', models.SmallIntegerField(default=0)),
                ('despachos_local', models.JSONField(null=True)),
                ('despachos_omniglobal', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
