# Generated by Django 3.1.7 on 2024-07-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_integraciones', '0002_auto_20240711_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='integraciones',
            name='ciudad',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='integraciones',
            name='latitud',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='integraciones',
            name='longitud',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='integraciones',
            name='pais',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='integraciones',
            name='provincia',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='integraciones',
            name='sector',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='integraciones',
            name='tipoCanal',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
