# Generated by Django 3.1.7 on 2024-07-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_integraciones', '0003_auto_20240716_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='integraciones',
            name='prefijo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
