# Generated by Django 3.1.7 on 2024-08-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_integraciones', '0004_integraciones_prefijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='integraciones',
            name='bodega_central',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
