# Generated by Django 3.1.7 on 2024-10-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_integraciones', '0005_integraciones_bodega_central'),
    ]

    operations = [
        migrations.AddField(
            model_name='integraciones',
            name='descripcion_direccion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='integraciones',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integraciones',
            name='direccion_mapa',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='integraciones',
            name='hora_atencion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
