# Generated by Django 3.1.7 on 2024-10-07 17:44

import apps.ADM.vittoria_integraciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_integraciones', '0006_auto_20241004_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='integraciones',
            name='imagen_principal',
            field=models.FileField(blank=True, null=True, upload_to=apps.ADM.vittoria_integraciones.models.upload_path),
        ),
    ]
