# Generated by Django 3.1.7 on 2024-07-05 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=150, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('tipoCliente', models.CharField(blank=True, max_length=150, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram', models.CharField(blank=True, max_length=150, null=True)),
                ('correo1', models.EmailField(blank=True, max_length=150, null=True)),
                ('correo2', models.EmailField(blank=True, max_length=150, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=150, null=True)),
                ('canal', models.CharField(blank=True, max_length=150, null=True)),
                ('canalOrigen', models.CharField(blank=True, max_length=255, null=True)),
                ('metodoPago', models.CharField(blank=True, max_length=255, null=True)),
                ('codigoProducto', models.CharField(blank=True, max_length=150, null=True)),
                ('nombreProducto', models.TextField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('tipoPrecio', models.CharField(blank=True, max_length=250, null=True)),
                ('nombreVendedor', models.CharField(blank=True, max_length=250, null=True)),
                ('confirmacionProspecto', models.CharField(blank=True, max_length=250, null=True)),
                ('tipoIdentificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=13, null=True)),
                ('nombreCompleto', models.CharField(blank=True, max_length=255, null=True)),
                ('callePrincipal', models.CharField(blank=True, max_length=255, null=True)),
                ('numeroCasa', models.CharField(blank=True, max_length=255, null=True)),
                ('calleSecundaria', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=255, null=True)),
                ('comentariosVendedor', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('subTotal', models.FloatField(null=True)),
                ('descuento', models.FloatField(null=True)),
                ('iva', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('courier', models.CharField(blank=True, max_length=255, null=True)),
                ('articulos', models.JSONField(null=True)),
                ('facturacion', models.JSONField(null=True)),
                ('envio', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ContactosDetalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=150, null=True)),
                ('valorUnitario', models.FloatField(null=True)),
                ('cantidad', models.PositiveIntegerField(null=True)),
                ('precio', models.FloatField(null=True)),
                ('codigo', models.CharField(max_length=250, null=True)),
                ('informacionAdicional', models.CharField(max_length=250, null=True)),
                ('descuento', models.FloatField(null=True)),
                ('impuesto', models.FloatField(null=True)),
                ('valorDescuento', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('contactoEncabezado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='mdm_contactos.contactos')),
            ],
        ),
    ]
