# Generated by Django 3.1.7 on 2024-07-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_contactos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactos',
            name='usuario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
