# Generated by Django 3.1.7 on 2024-08-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_contactos', '0002_auto_20240725_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='tipoContacto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
