# Generated by Django 3.1.7 on 2024-08-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_contactos', '0003_contactos_tipocontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='estadoGestion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
