# Generated by Django 3.1.7 on 2021-11-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gde_gestionEntrega', '0003_auto_20211112_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='codigo',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
