# Generated by Django 3.1.7 on 2021-11-18 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gde_gestionEntrega', '0004_oferta_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='codigoOferta',
        ),
    ]
