# Generated by Django 3.1.7 on 2024-10-22 14:47

import apps.MDP.mdrp_productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=150, null=True)),
                ('lote', models.CharField(blank=True, max_length=10, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('costoCompra', models.FloatField(blank=True, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to=apps.MDP.mdrp_productos.models.upload_path)),
                ('precioVentaA', models.FloatField(blank=True, null=True)),
                ('precioVentaB', models.FloatField(blank=True, null=True)),
                ('precioVentaC', models.FloatField(blank=True, null=True)),
                ('precioVentaD', models.FloatField(blank=True, null=True)),
                ('precioVentaE', models.FloatField(blank=True, null=True)),
                ('precioVentaF', models.FloatField(blank=True, null=True)),
                ('porcentaje_comision', models.IntegerField(blank=True, null=True)),
                ('valor_comision', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, default='Inactivo', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
