# Generated by Django 3.1.7 on 2024-10-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrp_productos', '0003_productos_fecha_confirmacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='verificarProducto',
            field=models.SmallIntegerField(default=0),
        ),
    ]
