# Generated by Django 3.1.7 on 2024-10-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrp_productos', '0004_productos_verificarproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precioLanding',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='precioLandingOferta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='precioOferta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='precioVentaBultos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
