# Generated by Django 3.1.7 on 2021-04-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endPoint', models.CharField(max_length=200, null=True)),
                ('modulo', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('accion', models.CharField(max_length=100, null=True)),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('dataEnviada', models.TextField(default='{}')),
                ('fechaFin', models.DateTimeField(null=True)),
                ('dataRecibida', models.TextField(default='{}')),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
