# Generated by Django 3.1.7 on 2021-08-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdo_gestionOferta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='fechaCompra',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='vigenciaOferta',
            field=models.IntegerField(max_length=150, null=True),
        ),
    ]
