# Generated by Django 3.1.7 on 2021-11-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdo_gestionOferta', '0004_auto_20211112_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='canalVentas',
            new_name='canal',
        ),
    ]
