# Generated by Django 3.1.7 on 2021-11-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdo_gestionOferta', '0005_auto_20211115_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='codigo',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
