# Generated by Django 3.1.7 on 2024-08-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsb_pedidos', '0002_superbarato_productoextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='superbarato',
            name='estadoGestion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
