# Generated by Django 3.1.7 on 2021-07-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=150)),
                ('subCategoria', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150, null=True)),
                ('codigoBarras', models.CharField(max_length=150)),
                ('refil', models.IntegerField(max_length=150)),
                ('stock', models.IntegerField(max_length=150)),
                ('caducidad', models.IntegerField(max_length=150)),
                ('costoCompra', models.FloatField(null=True)),
                ('precioVentaA', models.FloatField(null=True)),
                ('precioVentaB', models.FloatField(null=True)),
                ('precioVentaC', models.FloatField(null=True)),
                ('precioVentaD', models.FloatField(null=True)),
                ('precioVentaE', models.FloatField(null=True)),
                ('precioVentaBultos', models.FloatField(null=True)),
                ('alertaAbastecimiento', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
