# Generated by Django 3.1.7 on 2021-07-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='alertaAbastecimiento',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='caducidad',
            field=models.IntegerField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigoBarras',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='refil',
            field=models.IntegerField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='subCategoria',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
