# Generated by Django 3.1.7 on 2021-07-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0004_auto_20210719_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporterotacion',
            name='tipoRotacion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
