# Generated by Django 3.1.7 on 2021-07-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0005_auto_20210719_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporteRefil',
        ),
    ]
