# Generated by Django 3.1.7 on 2021-07-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0006_delete_reporterefil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='imagenes', to='mdp_productos.productos'),
        ),
    ]
