# Generated by Django 3.1.7 on 2021-07-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0007_auto_20210720_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteabastecimiento',
            name='mostrarAviso',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporteabastecimiento',
            name='notificacionEnviada',
            field=models.SmallIntegerField(default=0),
        ),
    ]
