# Generated by Django 3.1.7 on 2021-07-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_parametrizaciones', '0004_auto_20210721_1038'),
        ('mdp_productos', '0008_auto_20210720_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAvisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.CharField(max_length=150, null=True)),
                ('fechaCompra', models.DateTimeField(null=True)),
                ('productosVendidos', models.IntegerField(max_length=150, null=True)),
                ('alerta', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='productos',
            name='alertaAbastecimiento',
        ),
        migrations.AddField(
            model_name='productos',
            name='parametrizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mdp_parametrizaciones.parametrizaciones'),
        ),
    ]
