# Generated by Django 3.1.7 on 2021-07-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0010_auto_20210726_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fechaCaducidad',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='fechaElaboracion',
            field=models.DateTimeField(null=True),
        ),
    ]
