# Generated by Django 3.1.7 on 2021-07-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0011_auto_20210726_1241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lotes',
            new_name='IngresoProductos',
        ),
    ]
