# Generated by Django 3.1.7 on 2021-07-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0012_auto_20210727_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialavisos',
            name='precioVenta',
            field=models.FloatField(null=True),
        ),
    ]
