# Generated by Django 3.1.7 on 2021-07-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0013_historialavisos_precioventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='fechaCaducidad',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fechaElaboracion',
            field=models.DateField(null=True),
        ),
    ]
