# Generated by Django 3.1.7 on 2021-07-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0014_auto_20210728_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoproductos',
            name='fechaCaducidad',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ingresoproductos',
            name='fechaElaboracion',
            field=models.DateField(null=True),
        ),
    ]
