# Generated by Django 3.1.7 on 2021-10-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0016_auto_20211025_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
