# Generated by Django 3.1.7 on 2021-11-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0017_auto_20211026_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.CharField(default='Inactivo', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='refil',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportestock',
            name='fechaUltimaStock',
            field=models.DateField(null=True),
        ),
    ]
