# Generated by Django 3.1.7 on 2021-11-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0018_auto_20211105_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecaducidad',
            name='diasParaCaducar',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportecaducidad',
            name='fechaCaducidad',
            field=models.DateField(null=True),
        ),
    ]
