# Generated by Django 3.1.7 on 2021-11-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0019_auto_20211105_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteabastecimiento',
            name='cantidadSugeridaStock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reporteabastecimiento',
            name='fechaMaximaStock',
            field=models.DateField(null=True),
        ),
    ]
