# Generated by Django 3.1.7 on 2021-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0020_auto_20211108_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporterotacion',
            name='fechaFin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reporterotacion',
            name='fechaInicio',
            field=models.DateField(null=True),
        ),
    ]
