# Generated by Django 3.1.7 on 2021-11-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0021_auto_20211110_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='caducidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportecaducidad',
            name='diasParaCaducar',
            field=models.IntegerField(null=True),
        ),
    ]
