# Generated by Django 3.1.7 on 2024-01-22 20:31

import apps.MDP.mdp_productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0022_auto_20211116_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='caracteristicas',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=apps.MDP.mdp_productos.models.upload_path),
        ),
    ]
