# Generated by Django 3.1.7 on 2024-01-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0023_auto_20240122_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
