# Generated by Django 3.1.7 on 2024-01-22 20:49

import apps.MDP.mdp_productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0024_auto_20240122_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.MDP.mdp_productos.models.upload_path),
        ),
    ]
