# Generated by Django 3.1.7 on 2024-01-22 21:16

import apps.MDP.mdp_productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0025_productos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precioOferta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.MDP.mdp_productos.models.upload_path_video),
        ),
    ]
