# Generated by Django 3.1.7 on 2024-01-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0026_auto_20240122_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='courier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='lugarVenta',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
