# Generated by Django 3.1.7 on 2024-01-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0027_auto_20240124_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='lugarVenta',
        ),
        migrations.AddField(
            model_name='productos',
            name='envioNivelNacional',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productos',
            name='lugarVentaCiudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='lugarVentaProvincia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='courier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
