# Generated by Django 3.1.7 on 2024-03-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0029_auto_20240125_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='estadoLanding',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigoBarras',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='costoCompra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='envioNivelNacional',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.CharField(blank=True, default='Inactivo', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fechaCaducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fechaElaboracion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='lote',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioOferta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioVentaA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioVentaB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioVentaBultos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioVentaC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioVentaD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioVentaE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='refil',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='subCategoria',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='variableRefil',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
