# Generated by Django 3.1.7 on 2024-04-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0030_auto_20240319_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precioLanding',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='precioLandingOferta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
