# Generated by Django 3.1.7 on 2024-04-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0031_auto_20240401_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precioVentaF',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
