# Generated by Django 3.1.7 on 2024-04-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0032_productos_precioventaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
