# Generated by Django 3.1.7 on 2024-06-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0034_productos_idpadre'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='canal',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
