# Generated by Django 3.1.7 on 2024-06-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0035_productos_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='woocommerceId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
