# Generated by Django 3.1.7 on 2024-06-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0036_productos_woocommerceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='woocommerceId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
