# Generated by Django 3.1.7 on 2024-06-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0037_auto_20240613_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='woocommerceId',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
