# Generated by Django 3.1.7 on 2024-06-26 15:15

import apps.MDP.mdp_productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0039_productos_stockvirtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen_principal',
            field=models.FileField(blank=True, null=True, upload_to=apps.MDP.mdp_productos.models.upload_path),
        ),
    ]
