# Generated by Django 3.1.7 on 2024-07-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0041_auto_20240716_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='prefijo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
