# Generated by Django 3.1.7 on 2024-07-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0042_productos_prefijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='link_catalogo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
