# Generated by Django 3.1.7 on 2024-08-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0043_productos_link_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='link_tienda',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='link_catalogo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
