# Generated by Django 3.1.7 on 2024-10-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_productos', '0044_auto_20240802_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='porcentaje_comision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='valor_comision',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
