# Generated by Django 3.1.7 on 2021-05-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectosClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, null=True)),
                ('apellidos', models.CharField(max_length=150, null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('tipoCliente', models.CharField(max_length=150, null=True)),
                ('whatsapp', models.CharField(max_length=150, null=True)),
                ('facebook', models.CharField(max_length=150, null=True)),
                ('twitter', models.CharField(max_length=150, null=True)),
                ('instagram', models.CharField(max_length=150, null=True)),
                ('correo1', models.EmailField(max_length=150, null=True)),
                ('correo2', models.EmailField(max_length=150, null=True)),
                ('ciudad', models.CharField(max_length=150, null=True)),
                ('canal', models.CharField(max_length=150, null=True)),
                ('codigoProducto', models.CharField(max_length=150, null=True)),
                ('nombreProducto', models.CharField(max_length=150, null=True)),
                ('foto', models.CharField(max_length=250, null=True)),
                ('precio', models.FloatField()),
                ('tipoPrecio', models.CharField(max_length=250, null=True)),
                ('nombreVendedor', models.CharField(max_length=250, null=True)),
                ('confirmacionProspecto', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
