# Generated by Django 3.1.7 on 2021-10-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_prospectosClientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectosclientes',
            name='apellidos',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='canal',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='ciudad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='codigoProducto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='confirmacionProspecto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='correo1',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='correo2',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='nombreProducto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='nombreVendedor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='nombres',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='tipoCliente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='tipoPrecio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='twitter',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
