# Generated by Django 3.1.7 on 2021-11-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_prospectosClientes', '0002_auto_20211021_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectosclientes',
            name='identificacion',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
