# Generated by Django 3.1.7 on 2021-05-19 16:07

import apps.MDM.mdm_prospectosClientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_prospectosClientes', '0002_auto_20210519_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectosclientes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.MDM.mdm_prospectosClientes.models.upload_path),
        ),
    ]
