# Generated by Django 3.1.7 on 2021-05-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_prospectosClientes', '0003_prospectosclientes_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospectosclientes',
            name='foto',
        ),
    ]
