# Generated by Django 3.1.7 on 2021-11-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_prospectosClientes', '0004_prospectosclientes_nombrecompleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectosclientes',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prospectosclientes',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
