# Generated by Django 3.1.7 on 2024-01-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_prospectosClientes', '0007_prospectosclientes_tipoidentificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectosclientes',
            name='comentariosVendedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospectosclientes',
            name='nombreProducto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
