# Generated by Django 3.1.7 on 2024-01-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_prospectosClientes', '0010_prospectosclientesdetalles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospectosclientesdetalles',
            old_name='facturaEncabezado',
            new_name='prospectoClienteEncabezado',
        ),
    ]
