# Generated by Django 3.1.7 on 2024-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_prospectosClientes', '0013_prospectosclientes_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectosclientes',
            name='envio',
            field=models.JSONField(null=True),
        ),
    ]
