# Generated by Django 3.1.7 on 2024-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_prospectosClientes', '0014_prospectosclientes_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectosclientes',
            name='facturacion',
            field=models.JSONField(null=True),
        ),
    ]
