# Generated by Django 3.1.7 on 2024-03-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_prospectosClientes', '0015_prospectosclientes_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectosclientes',
            name='articulos',
            field=models.JSONField(null=True),
        ),
    ]
