# Generated by Django 3.1.7 on 2021-04-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vittoria_roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('estado', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(max_length=30)),
                ('compania', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vittoria_roles.roles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
