# Generated by Django 3.1.7 on 2021-04-26 16:48

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
