# Generated by Django 3.1.7 on 2021-05-17 17:45

import apps.ADM.vittoria_usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_usuarios', '0003_auto_20210510_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.ADM.vittoria_usuarios.models.upload_path),
        ),
    ]
