# Generated by Django 3.1.7 on 2024-06-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_usuarios', '0007_auto_20240322_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='canal',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
