# Generated by Django 3.1.7 on 2021-07-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_subCategorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorias',
            name='categoriaPadre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
