# Generated by Django 3.1.7 on 2021-07-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_subCategorias', '0002_auto_20210706_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorias',
            name='descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
