# Generated by Django 3.1.7 on 2021-10-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp_subCategorias', '0004_remove_subcategorias_categoriapadre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorias',
            name='codigoSubCategoria',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='estado',
            field=models.CharField(default='Inactivo', max_length=150),
        ),
    ]
