# Generated by Django 3.1.7 on 2024-08-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmb_despachos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='megabahia',
            name='montoPrevioPago',
            field=models.FloatField(null=True),
        ),
    ]
