# Generated by Django 3.1.7 on 2024-08-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmb_despachos', '0002_megabahia_montopreviopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='megabahia',
            name='nombreEnvio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
