# Generated by Django 3.1.7 on 2024-02-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturasEncabezados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPedido', models.CharField(blank=True, max_length=255, null=True)),
                ('estadoPedido', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaPedido', models.DateField(null=True)),
                ('notaCliente', models.CharField(blank=True, max_length=255, null=True)),
                ('nombresFacturacion', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidosFacturacion', models.CharField(blank=True, max_length=255, null=True)),
                ('empresaFacturacion', models.CharField(blank=True, max_length=255, null=True)),
                ('direccionFacturacion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudadFacturacion', models.CharField(blank=True, max_length=255, null=True)),
                ('provinciaFacturacion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigoPostalFacturacion', models.CharField(blank=True, max_length=255, null=True)),
                ('paisFacturacion', models.CharField(blank=True, max_length=255, null=True)),
                ('correoElectronicoFacturacion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefonoFacturacion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombresEnvio', models.CharField(blank=True, max_length=255, null=True)),
                ('apellidosEnvio', models.CharField(blank=True, max_length=255, null=True)),
                ('direccionEnvio', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudadEnvio', models.CharField(blank=True, max_length=255, null=True)),
                ('provinciaEnvio', models.CharField(blank=True, max_length=255, null=True)),
                ('codigoPostalEnvio', models.CharField(blank=True, max_length=255, null=True)),
                ('paisEnvio', models.CharField(blank=True, max_length=255, null=True)),
                ('metodoPago', models.CharField(blank=True, max_length=255, null=True)),
                ('descuentoCarrito', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotalPedido', models.CharField(blank=True, max_length=255, null=True)),
                ('metodoEnvio', models.CharField(blank=True, max_length=255, null=True)),
                ('importeEnvioPedido', models.CharField(blank=True, max_length=255, null=True)),
                ('importeReemsolsadoPedido', models.CharField(blank=True, max_length=255, null=True)),
                ('importeTotalPedido', models.CharField(blank=True, max_length=255, null=True)),
                ('importeTotalImpuestoPedido', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='Facturas',
            new_name='ArchivosFacturas',
        ),
        migrations.CreateModel(
            name='FacturasDetalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=255, null=True)),
                ('articulo', models.CharField(max_length=255, null=True)),
                ('nombreArticulo', models.CharField(max_length=255, null=True)),
                ('cantidad', models.CharField(max_length=255, null=True)),
                ('precio', models.CharField(max_length=255, null=True)),
                ('cupon', models.CharField(max_length=255, null=True)),
                ('importeDescuento', models.CharField(max_length=255, null=True)),
                ('importeImpuestoDescuento', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('facturaEncabezado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='facturacion.facturasencabezados')),
            ],
        ),
    ]
