# Generated by Django 3.1.7 on 2024-02-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_facturasdetalles_numeropedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasencabezados',
            name='estadoSRI',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
