# Generated by Django 3.1.7 on 2021-05-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_negocios', '0003_auto_20210520_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocios',
            name='estado',
            field=models.CharField(default='Inactivo', max_length=200),
        ),
        migrations.AddField(
            model_name='personalnegocios',
            name='estado',
            field=models.CharField(default='Inactivo', max_length=200),
        ),
    ]
