# Generated by Django 3.1.7 on 2021-05-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_negocios', '0006_auto_20210525_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalnegocios',
            name='tipoContacto',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
