# Generated by Django 3.1.7 on 2021-10-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_negocios', '0009_auto_20210624_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionesestablecimientosnegocios',
            name='referencia',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='negocios',
            name='actividadEconomica',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='negocios',
            name='correoOficina',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='negocios',
            name='correoPersonal',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='negocios',
            name='edadNegocio',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='negocios',
            name='gastosPromedioMensual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='negocios',
            name='googlePlus',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='negocios',
            name='ingresosPromedioMensual',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='negocios',
            name='nombreComercial',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='negocios',
            name='numeroEmpleados',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='negocios',
            name='numeroEstablecimientos',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='negocios',
            name='profesion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='negocios',
            name='razonSocial',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='negocios',
            name='ruc',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personalnegocios',
            name='correoEmpresa',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='personalnegocios',
            name='correoPersonal',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
