# Generated by Django 3.1.7 on 2024-09-24 14:22

import apps.MDM.mdm_asesores_comerciales.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vittoria_roles', '0003_auto_20210517_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsesoresComerciales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('canal', models.CharField(blank=True, max_length=250, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=apps.MDM.mdm_asesores_comerciales.models.upload_path)),
                ('nombres', models.CharField(blank=True, max_length=150, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('estado', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
                ('provincia', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp', models.CharField(max_length=30)),
                ('compania', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('saldo_asesor', models.FloatField(null=True)),
                ('nombre_banco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=13, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=100, null=True)),
                ('identificacion', models.CharField(max_length=13, null=True)),
                ('archivoCedula', models.FileField(blank=True, null=True, upload_to=apps.MDM.mdm_asesores_comerciales.models.upload_path)),
                ('movimientos', models.JSONField(null=True)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vittoria_roles.roles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
