# Generated by Django 3.1.7 on 2024-09-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_asesores_comerciales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesorescomerciales',
            name='idRol',
        ),
    ]
