# Generated by Django 3.1.7 on 2024-09-24 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mdm_asesores_comerciales', '0002_remove_asesorescomerciales_idrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesorescomerciales',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
