# Generated by Django 3.1.7 on 2024-09-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_asesores_comerciales', '0003_auto_20240924_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorescomerciales',
            name='fecha_nacimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
