# Generated by Django 3.1.7 on 2024-09-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_asesores_comerciales', '0004_asesorescomerciales_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorescomerciales',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
