# Generated by Django 3.1.7 on 2024-09-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_asesores_comerciales', '0005_asesorescomerciales_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesorescomerciales',
            name='compania',
        ),
        migrations.RemoveField(
            model_name='asesorescomerciales',
            name='username',
        ),
    ]
