# Generated by Django 3.1.7 on 2024-09-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_asesores_comerciales', '0006_auto_20240924_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesorescomerciales',
            name='usuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
