# Generated by Django 3.1.7 on 2024-09-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_asesores_comerciales', '0007_auto_20240925_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorescomerciales',
            name='observaciones',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
