# Generated by Django 3.1.7 on 2024-09-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_asesores_comerciales', '0008_asesorescomerciales_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorescomerciales',
            name='tipoIdentificacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
