# Generated by Django 3.1.7 on 2024-09-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_asesores_comerciales', '0010_auto_20240930_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientosasesores',
            name='numeroPedido',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movimientosasesores',
            name='saldo_egreso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientosasesores',
            name='saldo_ingreso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientosasesores',
            name='saldo_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientosasesores',
            name='saldo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
