# Generated by Django 3.1.7 on 2024-10-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_asesores_comerciales', '0011_auto_20240930_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientosasesores',
            name='numeroPedido',
        ),
        migrations.AddField(
            model_name='asesorescomerciales',
            name='numeroPedido',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
