# Generated by Django 3.1.7 on 2021-04-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vittoria_roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('idAccionPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vittoria_acciones.acciones')),
            ],
        ),
        migrations.CreateModel(
            name='AccionesPorRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('idAccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vittoria_acciones.acciones')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vittoria_roles.roles')),
            ],
        ),
        migrations.CreateModel(
            name='AccionesPermitidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
                ('idAccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vittoria_acciones.acciones')),
            ],
        ),
    ]
