# Generated by Django 3.1.7 on 2021-04-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_acciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones',
            name='codigo',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acciones',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
