# Generated by Django 3.1.7 on 2021-05-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_acciones', '0002_auto_20210429_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionesporrol',
            name='state',
            field=models.SmallIntegerField(default=0),
        ),
    ]
