# Generated by Django 3.1.7 on 2024-07-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionesEnvios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_origen', models.CharField(max_length=250, null=True)),
                ('ciudad_destino', models.CharField(max_length=250, null=True)),
                ('distancia', models.JSONField(null=True)),
                ('tamanio', models.SmallIntegerField(default=0, null=True)),
                ('peso', models.JSONField(null=True)),
                ('costo', models.SmallIntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
