# Generated by Django 3.1.7 on 2024-07-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_integraciones_envios', '0002_auto_20240715_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integracionesenvios',
            old_name='peso',
            new_name='peso_fin',
        ),
        migrations.RenameField(
            model_name='integracionesenvios',
            old_name='tamanio',
            new_name='peso_inicial',
        ),
        migrations.RemoveField(
            model_name='integracionesenvios',
            name='ciudad_destino',
        ),
        migrations.RemoveField(
            model_name='integracionesenvios',
            name='ciudad_origen',
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='courier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='formaPago',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='latitud',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='longitud',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='tamanio_fin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='tamanio_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='tiempo_entrega',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
