# Generated by Django 3.1.7 on 2024-07-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_integraciones_envios', '0003_auto_20240716_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracionesenvios',
            name='ciudadDestino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='provinciaDestino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
