# Generated by Django 3.1.7 on 2024-07-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_integraciones_envios', '0004_auto_20240717_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracionesenvios',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='sectorDestino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
