# Generated by Django 3.1.7 on 2024-07-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vittoria_integraciones_envios', '0005_auto_20240717_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracionesenvios',
            name='latitudDestino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='longitudDestino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='nombreCuenta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integracionesenvios',
            name='numeroCuenta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
