# Generated by Django 3.1.7 on 2024-04-29 15:25

import apps.WOOCOMMERCE.gdc_gestor_contactos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
                ('envioTotal', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('facturacion', models.JSONField(null=True)),
                ('envio', models.JSONField(null=True)),
                ('metodoPago', models.CharField(max_length=255)),
                ('numeroPedido', models.CharField(max_length=255)),
                ('articulos', models.JSONField(null=True)),
                ('envios', models.JSONField(null=True)),
                ('json', models.JSONField(null=True)),
                ('canal', models.CharField(blank=True, max_length=255, null=True)),
                ('codigoVendedor', models.CharField(blank=True, max_length=255, null=True)),
                ('urlMetodoPago', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('entregoProducto', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaEntrega', models.CharField(blank=True, max_length=255, null=True)),
                ('horaEntrega', models.CharField(blank=True, max_length=255, null=True)),
                ('calificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('metodoConfirmacion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigoConfirmacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaHoraConfirmacion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoFacturacion', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmacionEnvio', models.CharField(blank=True, max_length=255, null=True)),
                ('canalEnvio', models.CharField(blank=True, max_length=255, null=True)),
                ('archivoGuia', models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.gdc_gestor_contactos.models.upload_path)),
                ('fotoEmpaque', models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.gdc_gestor_contactos.models.upload_path)),
                ('videoEmpaque', models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.gdc_gestor_contactos.models.upload_path)),
                ('codigoCourier', models.CharField(blank=True, max_length=255, null=True)),
                ('nombreCourier', models.CharField(blank=True, max_length=255, null=True)),
                ('correoCourier', models.CharField(blank=True, max_length=255, null=True)),
                ('evidenciaFotoEmpaque', models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.gdc_gestor_contactos.models.upload_path)),
                ('evidenciaVideoEmpaque', models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.gdc_gestor_contactos.models.upload_path)),
                ('archivoMetodoPago', models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.gdc_gestor_contactos.models.upload_path)),
                ('verificarPedido', models.BooleanField(default=False)),
                ('numeroGuia', models.CharField(blank=True, max_length=255, null=True)),
                ('verificarGeneracionGuia', models.BooleanField(default=False)),
                ('fechaEmpacado', models.CharField(blank=True, max_length=255, null=True)),
                ('guiServiEntrega', models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.gdc_gestor_contactos.models.upload_path)),
                ('tipoPago', models.CharField(blank=True, max_length=255, null=True)),
                ('evidenciaPago', models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.gdc_gestor_contactos.models.upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
