# Generated by Django 3.1.7 on 2024-05-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_gestor_contactos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='numeroComprobante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
