# Generated by Django 3.1.7 on 2024-05-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_gestor_contactos', '0003_auto_20240506_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='numTransaccionTransferencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactos',
            name='totalCobroEfectivo',
            field=models.FloatField(null=True),
        ),
    ]
