# Generated by Django 3.1.7 on 2024-06-04 22:03

import apps.WOOCOMMERCE.gdc_gestor_contactos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_gestor_contactos', '0004_auto_20240506_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='fotoCupon',
            field=models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.gdc_gestor_contactos.models.upload_path),
        ),
    ]
