# Generated by Django 3.1.7 on 2024-07-01 16:52

import apps.WOOCOMMERCE.gdc_gestor_contactos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_gestor_contactos', '0005_contactos_fotocupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='archivoFormaPagoCredito',
            field=models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.gdc_gestor_contactos.models.upload_path),
        ),
        migrations.AddField(
            model_name='contactos',
            name='numTransaccionCredito',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='formaPago',
            field=models.JSONField(null=True),
        ),
    ]
