# Generated by Django 3.1.7 on 2024-07-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_gestor_contactos', '0006_auto_20240701_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='montoCredito',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contactos',
            name='montoTransferencia',
            field=models.FloatField(null=True),
        ),
    ]
