# Generated by Django 3.1.7 on 2024-07-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_gestor_contactos', '0007_auto_20240708_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='fechaCargaFormaPago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
