# Generated by Django 3.1.7 on 2024-07-31 14:41

import apps.WOOCOMMERCE.gdc_gestor_contactos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_gestor_contactos', '0008_contactos_fechacargaformapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='archivoFactura',
            field=models.FileField(blank=True, null=True, upload_to=apps.WOOCOMMERCE.gdc_gestor_contactos.models.upload_path),
        ),
        migrations.AddField(
            model_name='contactos',
            name='montoSubtotalCliente',
            field=models.FloatField(null=True),
        ),
    ]
