# Generated by Django 3.1.7 on 2024-07-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_gestor_contactos', '0009_auto_20240731_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='fechaEmisionFactura',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contactos',
            name='motivoNegacionPedido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
