# Generated by Django 3.1.7 on 2024-08-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_gestor_contactos', '0012_auto_20240808_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='numeroComprobanteQueja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
