# Generated by Django 3.1.7 on 2024-08-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_gestor_contactos', '0014_contactos_montosubtotalaprobadoqueja'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='comision',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contactos',
            name='comisionFinal',
            field=models.FloatField(null=True),
        ),
    ]
